AllCops:
  Exclude:
    - config/unicorn.rb
    - db/**/*
    - '**/Guardfile'
  RunRailsCops: true

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20
