language: ruby
rvm:
  - 2.3.0
before_install:
  - sudo apt-get -qq update
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rspec spec/
env:
  - DB=sqlite
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database medical_office_test;'
bundler_args: --binstubs=./bundler_stubs
