require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BankDepositsController do

  # This should return the minimal set of attributes required to create a valid
  # BankDeposit. As you add validations to BankDeposit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "type" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BankDepositsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bank_deposits as @bank_deposits" do
      bank_deposit = BankDeposit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bank_deposits).should eq([bank_deposit])
    end
  end

  describe "GET show" do
    it "assigns the requested bank_deposit as @bank_deposit" do
      bank_deposit = BankDeposit.create! valid_attributes
      get :show, {:id => bank_deposit.to_param}, valid_session
      assigns(:bank_deposit).should eq(bank_deposit)
    end
  end

  describe "GET new" do
    it "assigns a new bank_deposit as @bank_deposit" do
      get :new, {}, valid_session
      assigns(:bank_deposit).should be_a_new(BankDeposit)
    end
  end

  describe "GET edit" do
    it "assigns the requested bank_deposit as @bank_deposit" do
      bank_deposit = BankDeposit.create! valid_attributes
      get :edit, {:id => bank_deposit.to_param}, valid_session
      assigns(:bank_deposit).should eq(bank_deposit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BankDeposit" do
        expect {
          post :create, {:bank_deposit => valid_attributes}, valid_session
        }.to change(BankDeposit, :count).by(1)
      end

      it "assigns a newly created bank_deposit as @bank_deposit" do
        post :create, {:bank_deposit => valid_attributes}, valid_session
        assigns(:bank_deposit).should be_a(BankDeposit)
        assigns(:bank_deposit).should be_persisted
      end

      it "redirects to the created bank_deposit" do
        post :create, {:bank_deposit => valid_attributes}, valid_session
        response.should redirect_to(BankDeposit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bank_deposit as @bank_deposit" do
        # Trigger the behavior that occurs when invalid params are submitted
        BankDeposit.any_instance.stub(:save).and_return(false)
        post :create, {:bank_deposit => { "type" => "invalid value" }}, valid_session
        assigns(:bank_deposit).should be_a_new(BankDeposit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BankDeposit.any_instance.stub(:save).and_return(false)
        post :create, {:bank_deposit => { "type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bank_deposit" do
        bank_deposit = BankDeposit.create! valid_attributes
        # Assuming there are no other bank_deposits in the database, this
        # specifies that the BankDeposit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BankDeposit.any_instance.should_receive(:update).with({ "type" => "1" })
        put :update, {:id => bank_deposit.to_param, :bank_deposit => { "type" => "1" }}, valid_session
      end

      it "assigns the requested bank_deposit as @bank_deposit" do
        bank_deposit = BankDeposit.create! valid_attributes
        put :update, {:id => bank_deposit.to_param, :bank_deposit => valid_attributes}, valid_session
        assigns(:bank_deposit).should eq(bank_deposit)
      end

      it "redirects to the bank_deposit" do
        bank_deposit = BankDeposit.create! valid_attributes
        put :update, {:id => bank_deposit.to_param, :bank_deposit => valid_attributes}, valid_session
        response.should redirect_to(bank_deposit)
      end
    end

    describe "with invalid params" do
      it "assigns the bank_deposit as @bank_deposit" do
        bank_deposit = BankDeposit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BankDeposit.any_instance.stub(:save).and_return(false)
        put :update, {:id => bank_deposit.to_param, :bank_deposit => { "type" => "invalid value" }}, valid_session
        assigns(:bank_deposit).should eq(bank_deposit)
      end

      it "re-renders the 'edit' template" do
        bank_deposit = BankDeposit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BankDeposit.any_instance.stub(:save).and_return(false)
        put :update, {:id => bank_deposit.to_param, :bank_deposit => { "type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bank_deposit" do
      bank_deposit = BankDeposit.create! valid_attributes
      expect {
        delete :destroy, {:id => bank_deposit.to_param}, valid_session
      }.to change(BankDeposit, :count).by(-1)
    end

    it "redirects to the bank_deposits list" do
      bank_deposit = BankDeposit.create! valid_attributes
      delete :destroy, {:id => bank_deposit.to_param}, valid_session
      response.should redirect_to(bank_deposits_url)
    end
  end

end
